### PR TITLE
Array support convert to collection

### PR DESCRIPTION
**Pull request by storyn26383**
For example:

```javascript
[1, 2, 3].toCollection().sum() // 6
```

### CODE REVIEW

**Comment by ecrmnn** [comment]
Thanks @storyn26383 

Can we add this for objects as well?

**Comment by storyn26383** [comment]
Do you mean `Object.toCollection({ a: 1, b: 2, c: 3 })` ?
But I think use `collect({ a: 1, b: 2, c: 3 })` is much better.

**Comment by ecrmnn** [comment]
Thank you for this @storyn26383 

I would like to keep it simple and clean, so I'm gonna stick with only ``collect()``.

Please contribute again. This just didn't fit the project.

**Comment by storyn26383** [comment]
Ok, so sad, thanks for reviewing.

**Pull request closed without merging**
