### PR TITLE
add defaultValue to first(), pull() and last()

### LINKED ISSUE #148: first() is not inline with the laravel version
hey,

to stay inline with laravel\collection we should update the `first` method to match the laravel one

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Arr.php#L154-L181

basicly update the function to

`first(key|callback, default|callback)`

i try to make a PR

### PR DESCRIPTION
**Pull request by Helfull**
the `first` method should now be back in sync with the laravel version

FIx for Issue #148

### CODE REVIEW

**Comment by ecrmnn** [comment]
Woah, I was certain that I added that functionality. Thanks a lot for finding this, @Helfull!

Now that I had a closer look, both ``last()`` and ``pull()`` are also missing ``defaultValue``.
Any chance you could implement that too?

**Comment by Helfull** [comment]
there you go :-),

i also did in the same go update them to use the helper function `values`
also added a helper function to check if something is empty

**Comment by ecrmnn** [comment]
Heads up: Just added this [``newline-before-return``](https://eslint.org/docs/rules/newline-before-return) to .eslintrc.js

**Comment by Helfull** [comment]
the logic was in there but used on multiple methods, but yeah can move it

**Pull request merged**
