### PR TITLE
Add `firstOrFail` and `sole` methods

### PR DESCRIPTION
**Pull request by stevebauman**
## Description

This PR introduces the `firstOrFail()` and `sole()` methods, which shares a similar API to Laravel Collections.

## Examples

**firstOrFail:**
```js
collect().firstOrFail();

// Error ("Item not found.")  thrown
```

```js
collect([1]).firstOrFail();

// 1
```

**sole:**

```js
collect([1, 2]).sole();

// Error ("Multiple items found.") thrown
```

```js
collect([1, 2]).sole(item => item > 2);

// Error ("Item not found.") thrown
```

```js
collect([1, 2, 3, 4]).sole(item => item > 3);

// 4
```

```js
collect([1]).sole();

// 1
```

Let me know if you have any questions/comments/concerns. Thanks for your time! ❤️ 

---

Note: I didn't create custom errors to throw (i.e. `ItemNotFoundError`/`MultipleItemsFoundError`) like Laravel throws for its exceptions. Let me know if you'd like this implemented 👍

### CODE REVIEW

**Comment by ecrmnn** [comment]
Hi, @stevebauman 

Thank for a great PR.
I have a couple of requests to be compliant with the Laravel API.

Both methods are missing parameters.

#### Missing paramenters for `firstOrFail` method.
Look at Laravel source; 
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Collection.php#L1180
Add tests where all parameters are used in different ways.
You may look at Laravel test suite; 
https://github.com/laravel/framework/blob/8.x/tests/Support/SupportCollectionTest.php#L161

#### Missing parameters for `sole` method.
Look at Laravel source; 
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Collection.php#L1151
Add tests where all parameters are used in different ways.
You may look at Laravel test suite; 
https://github.com/laravel/framework/blob/8.x/tests/Support/SupportCollectionTest.php#L75

**Comment by stevebauman** [comment]
Hey @ecrmnn! Ok I can add the parameters in.

Though, the following methods in CollectJS don't follow the same parameter convention that exists in Laravel:

- `contains()` - Missing operator
- `doesntContain()` - Missing operator
- `duplicates()` - Missing callback
- `every()` - Missing operator and value

**Review by hlaCk — APPROVED** [review]

**Review by mPhpMaster — APPROVED** [review]

**Comment by ecrmnn** [comment]
Great!

They were correct once, but Laravel Collections keep getting improved all the time so unfortunetly some methods are missing some parameters. I'm sporadically working on updating these.

For new methods though, we should follow the current API.

**Comment by stevebauman** [comment]
Ok, I've refactored the methods to follow the Laravel API to the "T". I've also refactored the tests to be identical to Laravel's test suite that you've linked.

This refactoring also includes the extraction of the `where` comparisons to a new helper method named directly after Laravel's helper method `operatorForWhere`, which returns a "filter" callback, executing the comparison operation against the given operator.

Let me know if you'd like any further adjustments. Thanks for your time! ❤️

**Pull request merged**
