### PR TITLE
Accept a function as 'average' method argument

### PR DESCRIPTION
**Pull request by DaLooK**
Check if 'key' inside 'average' method is a function. If so, pass it as it is to the 'sum' method and divide the result over the items length

### CODE REVIEW

**Comment by ecrmnn** [comment]
Hi @DaLooK 
Thanks for this PR.

The goal for Collect.js is to mirror the API of Laravel Collections.

Do you know if this is implemented in Laravel Collection?

**Comment by DaLooK** [comment]
Yes, the Laravel collection accepts a callback as argument.

https://github.com/illuminate/collections/blob/1e70a82b09cffea032d336ee720056cf05dd31d2/Collection.php#L75

On 30 Apr 2021, at 7:34 a.m., Daniel Eckermann ***@***.***> wrote:

﻿

Hi @DaLooK<https://github.com/DaLooK>
Thanks for this PR.

The goal for Collect.js is to mirror the API of Laravel Collections.

Do you know if this is implemented in Laravel Collection?

**Comment by DaLooK** [comment]
Yes, the Laravel collection accepts a callback as argument.

https://github.com/illuminate/collections/blob/1e70a82b09cffea032d336ee720056cf05dd31d2/Collection.php#L75

**Comment by ecrmnn** [comment]
Great! Could you please provide a test for this also?

**Pull request merged**
