### PR TITLE
Add CDNJS version badge in README.md

### PR DESCRIPTION
**Pull request by extend1994**
The badge shows the latest lib version on CDNJS and gives a link of it.

### CODE REVIEW

**Comment by ecrmnn** [comment]
Hi @extend1994.

Will the version hosted on CDNJS be automatically updated?

**Comment by extend1994** [comment]
Hi @ecrmnn Yes, when you release a new version on GitHub, cdnjs will update it too 🙂

**Comment by ecrmnn** [comment]
How long before cdn updates? Released 4.0.12 around 12 hours ago, but cdn is still at 4.0.11

**Comment by extend1994** [comment]
Seems like 4.0.12 was only release on npm. 
It gets update only if 4.0.12 is released(tag) on GitHub because collect.js is set "git auto-update" on cdnjs :disappointed_relieved: If it doesn't bother you, please also release the version on GitHub.
"auto-update" is a mechanism to allow cdnjs update the libraries from GitHub **_or_** npm. For more details, you can refer https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md.
Or if you want to use npm as the source of cdnjs auto-update, I can help you that :slightly_smiling_face:

**Pull request merged**
