### PR TITLE
index.d.ts complemented types file, not everything but at least something

### PR DESCRIPTION
**Pull request by sosise**

### CODE REVIEW

**Comment by igor875126** [comment]
Hey Danile, what about pull request, will you merge it?

**Comment by ecrmnn** [comment]
Hi. 

It's missing a lot of definitions.
I would like to have them all defined before merging.

Could you add them?

**Comment by igor875126** [comment]
> Hi.
> 
> It's missing a lot of definitions.
> I would like to have them all defined before merging.
> 
> Could you add them?

Hey again,

what I did is:
1. Added some definitions, which were originally not there
2. Edited previous definitions which were wrong.

I could add missing definitions, but not all at once, because of a lack of time, so let's add them gradually.

What do you think about it? I mean this pull request makes definition file better than it was originally ;)

**Comment by ecrmnn** [comment]
Closing this for now. Feel free to pick this up and complete the definitions.

**Pull request closed without merging**
