### PR TITLE
Improved `first`

### LINKED ISSUE #294: `first` passes a `null` argument to the function if the items inside the collection are organized in an object
Example:

```js
collect({
  one: 1,
  two: 2
}).first((item) => {
  console.log(item); // item is null
  return item > 5;
})
```

This instead works:
```js
collect([1, 2, '3']).first((item) => {
  console.log(item); // Item is 1, then 2 and finally '3'
  return item > 5;
})
```

### PR DESCRIPTION
**Pull request by maicol07**
- Added support for `this.items` as an object
- Added the second key parameter to the function

Closes #294

### CODE REVIEW

**Comment by ecrmnn** [comment]
Thanks 🙌

Please add one or two new tests to prove your solution.
Also, your changes fails exsisting tests, please make sure that they pass.

https://app.travis-ci.com/github/ecrmnn/collect.js/builds/245443582

**Comment by maicol07** [comment]
@ecrmnn done! There's an issue regarding the build. I think that's because I've used the `for...of` loop, however it's the best way to fix this issue

**Comment by ecrmnn** [comment]
`for ... of` is not allowed in the ESLint config. 
You'll need to change your code.

**Comment by maicol07** [comment]
@ecrmnn done! Tests work!

**Pull request merged**
