### PR TITLE
Improve clone helper to avoid modify original input 

### PR DESCRIPTION
**Pull request by khuyennguyen7007**
I discovered an issue when retrieve result from collect. It can be modified the original input.
```
var users = [{name: "John", age: 30}, {name: "Steve", age: 20}];
var first = collect(users).where('age', 30).first();
first.age = 20;
users[0].age == 20; // true
```

### CODE REVIEW

**Comment by ecrmnn** [comment]
Thanks for your contribution. This looks good. I'm currently on vacation and will merge when I'm back.

**Comment by khuyennguyen7007** [comment]
Thanks for your attention. I'm new to Laravel framework and very interested in Laravel Collection. It's good to know that there is something like that in javascript. Wish you have a great vacation!

**Comment by ecrmnn** [comment]
I don't know why Travis doesn't fail this build, but your change is causing a memory leak.
Please fix your implementation.

https://travis-ci.org/ecrmnn/collect.js/jobs/586550809

**Comment by ecrmnn** [comment]
Bump

**Comment by ecrmnn** [comment]
Closing due to inactivity

**Pull request closed without merging**
