### PR TITLE
UMD pattern

### PR DESCRIPTION
**Pull request by georapbox**
Universal Module Definition pattern so that the library is both AMD and
CommonJS compatible and as well as supporting the old-style “global”
variable definition.

### CODE REVIEW

**Comment by ecrmnn** [comment]
Awesome. Thanks @georapbox.
Could you just add a few tests so that we get this covered by the test suite?
I don't now how it would be best to test this.

**Comment by mikeerickson** [comment]
+1

**Comment by georapbox** [comment]
To be honest, I don't know how this could be covered by a unit test. It's just about the way that a module is exported in different environments. For example, Mocha utilizes the CommonJS pattern and loads the module successfully and all existing tests pass as expected. So, if we had to test it we should emulate somehow 3 different environments. Maybe someone from the community has a better approach?

**Comment by mikeerickson** [comment]
@georapbox Good point!  The best way to test this would be to create browser tests (as that is where UMD is typically used).  However, it would then mean create a full test suite.

I could put forth the effort for creating a UMD testing workflow for the project and use the code in this PR for UMD module.

@ecrmnn Are you keen for more substantial contribution to the overall project?

**Comment by ecrmnn** [comment]
@mikeerickson Sounds good 👍  I'm open for an UMD testing workflow. We need tests before implementing this.

**Comment by ecrmnn** [comment]
#112

**Pull request closed without merging**
